name: Build iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby (for CocoaPods)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods || true
        pod install || true

    - name: Build app
      run: |
        xcodebuild -project Starfish.xcodeproj -scheme Starfish -sdk iphoneos -configuration Release archive -archivePath ${{github.workspace}}/build/Starfish.xcarchive
        xcodebuild -exportArchive -archivePath ${{github.workspace}}/build/Starfish.xcarchive -exportPath ${{github.workspace}}/build/export -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v2
      with:
        name: starfish-ipa
        path: build/export/*.ipa
