name: Build iOS App (No Signing)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Set up Ruby (for CocoaPods)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies (CocoaPods)
      run: |
        sudo gem install cocoapods || true
        pod install || true

    - name: Install Pod Dependencies
      run: |
        cd Starfish
        pod install

    - name: Build archive (no signing)
      run: |
        xcodebuild -project Starfish.xcodeproj \
          -scheme Starfish \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          archive -archivePath build/Starfish.xcarchive

    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath build/Starfish.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/export

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: starfish-ipa
        path: build/export/*.ipa
